### ISSUE TITLE
How to configure for an Android project with multiple subprojects?

### ISSUE THREAD

**Issue by dmfrey** [Minecrell/licenser#1]
How would you best configure this plugin for use with and Android Studio gradle project with multiple subprojects?

**Comment by Minecrell** [comment]
I'm pretty sure it does not support Android currently, but I can take a look later and see if I can make it work. :)

**Comment by Minecrell** [comment]
I've made some changes for Android support, it should work as of licenser 0.2. For your multiple subprojects, here is how I'd suggest setting it up:

1. Add the license you want to apply as header to your root project folder, e.g. in a `LICENSE` file.
2. Open your root `build.gradle` (not one of the subprojects), and configure it like this:

    ```gradle
    buildscript {
        repositories {
            jcenter()
        }
        dependencies {
            classpath 'com.android.tools.build:gradle:2.1.0'
        }
    }

    plugins {
        id 'net.minecrell.licenser' version '0.2'
    }

    allprojects {
        repositories {
            jcenter()
        }

        // Apply license header plugin
        apply plugin: 'net.minecrell.licenser'

        license {
            header = rootProject.file('LICENSE')
        }
    }
    ```

That will apply the plugin to all your subprojects. Some of the parts mentioned above should already exist for a project created by Android Studio, so just merge it in.

I'd appreciate if you could tell me if it works for you, Android support is still experimental.

**Comment by dmfrey** [comment]
Great. Thank you. I will try this later and let you know.

**Comment by Minecrell** [comment]
@dmfrey Any news? Otherwise I will close this for now, it should work fine. :)

**Comment by dmfrey** [comment]
Sorry, I haven't had a chance to set it up yet, and I am going to be
somewhat offline for the next week. You can close if you like, I will
revisit it when I am back up and running.
