### ISSUE TITLE
Feature request - Variable substitution

### ISSUE THREAD

**Issue by kpopovic** [Minecrell/licenser#2]
Hello,

your plugin would be nicer it could support Variable substitution.

Example:

    Copyright (C) ${year} ${name} <${email}>
Will be completed with this extension block, the key is adding them via extra properties:

```gradle
license {
    ext.year = Calendar.getInstance().get(Calendar.YEAR)
    ext.name = 'Company'
    ext.email = 'support@company.com'
}
```

**Comment by Minecrell** [comment]
Thank you for your request! Fortunately this is already possible using your syntax!

```gradle
license {
    ext.year = Calendar.getInstance().get(Calendar.YEAR)
    ext.name = 'Company'
    ext.email = 'support@company.com'
    header = file('LICENSE')
}
```
Using this LICENSE:
```
Copyright (C) ${year} ${name} <${email}>
```
Results in:
```java
/*
 * Copyright (C) 2016 Company <support@company.com>
 */
```

**Comment by Minecrell** [comment]
I just realized it's not mentioned in the README, I will fix that soon :)

**Comment by kpopovic** [comment]
Hello,
I will try it today and verify if it works.

Best Regards,
Krešimir (from Croatia)

**Comment by kpopovic** [comment]
Hello,
I confirm it works !
:+1:
