### ISSUE TITLE
IllegalStateException Failed to find end of block comment

### ISSUE THREAD

**Issue by msrd0** [Minecrell/licenser#5]
I'm trying to use this plugin together with generated sources. The header of the generated source file looks like this:

    /* GENERATED FILE - DO NOT EDIT */

Running the `licenseFormat` task I get the following exception:

```
Failed to update license header in generated/file.kt
java.lang.IllegalStateException: Failed to find end of block comment in /home/user/git/project/generated/file.kt
```

The entire stack trace is [attached](https://github.com/Minecrell/licenser/files/1385175/exception.txt).

Since I absolutely don't care about the header of a generated file, I tried excluding the `generated` directory:

```gradle
license {
	// ...
	exclude '**/generated/**'
}
```

However, this didn't change anything

**Comment by Minecrell** [comment]
How do you include the generated sources in the Gradle build. Do you just add it as separate source directory or as entirely new source set?

Note that these exclusions are based on the source directory, not on the root project directory. You can only use them to exclude specific packages or files with a special name.

Let's consider the following example:

```
src/main/java
    - net/minecrell/test/Test.java
generated
    - net/minecrell/test/gen/Generated.java
```

You could exclude `net/minecrell/test/gen/**` (the package) but you cannot exclude using `**/generated/**` directly. The exclusions only match the file path in the source directory.

Nevertheless, licenser shouldn't fail on files with this header. I will check if I can reproduce this problem and see if I can find a solution.

**Comment by msrd0** [comment]
I added it to the existing source set. What would you suggest to exclude all files in that directory?

**Comment by Minecrell** [comment]
If you can, the best solution would be to generate the sources so they are in a specific package only for generated sources. That way you can just exclude the package as shown above.

**Comment by msrd0** [comment]
Well, the generated files are kotlin, so the package can be different from the folders. In my case the generated files just end up in the root directory of the generated source folder, so I'd need a way to exclude an entire source folder.

**Comment by Minecrell** [comment]
@msrd0 If the folder doesn't matter for the package, couldn't you just add them into an additional "generated" directory? That way you can exclude them normally.

Currently, there is no way to exclude specific source directories of a source set, you can only exclude files/directories **within** a source set.

**Comment by msrd0** [comment]
Ok thanks for the explanation. Still I'd love to see a feature to exclude certain source directories, not only subdirectories

**Comment by Minecrell** [comment]
@msrd0 I see your point. Feel free to open a new issue for adding that feature and I will consider it as soon as I have time. :)

**Comment by msrd0** [comment]
There you go: #6
