### ISSUE TITLE
Add support for handing every file in project rootDir

### ISSUE THREAD

**Issue by DemonWav** [Minecrell/licenser#7]
Some files that need licensing aren't contained in source sets.

**Comment by Minecrell** [comment]
It doesn't automatically add every single file in the project, because that would be stupid imo, but you can easily create tasks for additional files now.

E.g. to format a bunch of Gradle files:
```kts
license {
    tasks {
        "gradle" {
            files = project.files("build.gradle.kts", "settings.gradle.kts", "gradle.properties")
        }
    }
}
```
